# Generated by Django 3.2 on 2023-01-23 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(allow_unicode=True)),
                ('name', models.CharField(max_length=100)),
                ('logo', models.ImageField(blank=True, default='no-image.jpg', height_field='imageheight', null=True, upload_to='static/images/logos/', width_field='imagewidth')),
                ('imagewidth', models.PositiveIntegerField(default=50, editable=False)),
                ('imageheight', models.PositiveIntegerField(default=50, editable=False)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('published_at', models.DateTimeField()),
            ],
            options={
                'verbose_name_plural': 'Brand',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(allow_unicode=True)),
                ('name', models.CharField(max_length=100)),
                ('desc', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('published_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a Product Color', max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Product Colors',
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('published_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(allow_unicode=True)),
                ('name', models.CharField(max_length=150)),
                ('desc', models.TextField(blank=True, max_length=255, null=True)),
                ('mini_desc', models.CharField(max_length=200)),
                ('price', models.PositiveBigIntegerField(blank=True, null=True)),
                ('cover', models.ImageField(default='no-image.jpg', height_field='imageheight', upload_to='static/images/products/20230123-090457', width_field='imagewidth')),
                ('pic1', models.ImageField(blank=True, default='no-image.jpg', null=True, upload_to='static/images/products/20230123 - 090457')),
                ('pic2', models.ImageField(blank=True, default='no-image.jpg', null=True, upload_to='static/images/products/20230123 - 090457')),
                ('pic3', models.ImageField(blank=True, default='no-image.jpg', null=True, upload_to='static/images/products/20230123 - 090457')),
                ('pic4', models.ImageField(blank=True, default='no-image.jpg', null=True, upload_to='static/images/products/20230123 - 090457')),
                ('imagewidth', models.PositiveIntegerField(default=401, editable=False)),
                ('imageheight', models.PositiveIntegerField(default=401, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('published_at', models.DateTimeField()),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.category')),
                ('color', models.ManyToManyField(help_text='Select Color of the product', to='shop.Color')),
                ('discount', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payment.discount')),
                ('inventory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.inventory')),
            ],
            options={
                'verbose_name_plural': 'Products',
            },
        ),
    ]
