# Generated by Django 3.2 on 2023-01-30 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20230130_0736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='imageheight',
            field=models.PositiveIntegerField(default=40, editable=False),
        ),
        migrations.AlterField(
            model_name='brand',
            name='imagewidth',
            field=models.PositiveIntegerField(default=40, editable=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='cover',
            field=models.ImageField(default='no-image.jpg', height_field='imageheight', upload_to='static/images/products/20230130-130741', width_field='imagewidth'),
        ),
        migrations.AlterField(
            model_name='product',
            name='pic1',
            field=models.ImageField(blank=True, default='no-image.jpg', null=True, upload_to='static/images/products/20230130 - 130741'),
        ),
        migrations.AlterField(
            model_name='product',
            name='pic2',
            field=models.ImageField(blank=True, default='no-image.jpg', null=True, upload_to='static/images/products/20230130 - 130741'),
        ),
        migrations.AlterField(
            model_name='product',
            name='pic3',
            field=models.ImageField(blank=True, default='no-image.jpg', null=True, upload_to='static/images/products/20230130 - 130741'),
        ),
        migrations.AlterField(
            model_name='product',
            name='pic4',
            field=models.ImageField(blank=True, default='no-image.jpg', null=True, upload_to='static/images/products/20230130 - 130741'),
        ),
    ]
